language: python
python:
    - "3.5"
    - "3.6"
    - "3.7-dev"
before_install:
    - sudo apt-get update
    - sudo apt-get install -y libgmp-dev libmpfr-dev libmpc-dev libffi-dev build-essential python3-pip python3-dev
    - pip install coveralls
script: coverage run -m unittest -v
after_success:
    - coveralls
